### Loading Data into Pandas

In [13]:
import pandas as pd

df = pd.read_csv('pokemon_data.csv') # Data loaded in object type called dataframe

print(df.head(3)) # Default is 5
print(df.tail(3))

# Can load in data of various formats
df_xlsx = pd.read_excel('pokemon_data.xlsx')
df_txt = pd.read_csv('pokemon_data.txt', delimiter='\t') # File is tab-separated

   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
0           1      False
1           1      False
2           1      False
       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170
799  721            Volcanion     Fire  Water  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
797      130     70           6       True
798      130     80           6       True
799       90     70           6       True

### Reading Data in Pandas

In [109]:
# Read headers
print(df.columns)

# Read specific columns
print(df['Name'][0:5])
print(df.Name[0:5]) # Only works for one-word column names

# Read multiple columns
print(df[['Name', 'Type 1', 'HP']])

# Read specific rows
print(df.iloc[1]) # iloc stands for integer location
print(df.iloc[0:4])

# Iterate through rows
for index, row in df[:20].iterrows():
    print(index, row['Name'])

# Find rows by content (instead of integer location)
print(df.loc[df['Type 1'] == "Fire"])

# Read a specific location (R,C)
print(df.iloc[2,1])

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'count'],
      dtype='object')
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object
                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
Total             405
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
count               1
Name: 1, dtype: object
   #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49
1  2                Ivysaur  Grass  Poison    405  60      62       63
2  3               Venusaur  Grass  Poison    525  80      82       83
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  count
0       65       65     45           1      False      1
1       80       80     60           1      False      1
2      100      100     80           1      False      1
3      122      120     80           1      False      1
0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
       #                       Name Type 1    Type 2  Total   HP  Attack  \
4      4                 Charmander   Fire       NaN    309   39      52
5      5                 Charmeleon   Fire       NaN    405   58      64
6      6                  Charizard   Fire    Flying    534   78      84
7      6  CharizardMega Charizard X   Fire    Dragon    634   78     130
8      6  CharizardMega Charizard Y   Fire    Flying    634   78     104
42    37                     Vulpix   Fire       NaN    299   38      41
43    38                  Ninetales   Fire       NaN    505   73      76
63    58                  Growlithe   Fire       NaN    350   55      70
64    59                   Arcanine   Fire       NaN    555   90     110
83    77                     Ponyta   Fire       NaN    410   50      85
84    78                   Rapidash   Fire       NaN    500   65     100
135  126                     Magmar   Fire       NaN    495   65      95
147  136                    Flareon   Fire       NaN    525   65     130
158  146                    Moltres   Fire    Flying    580   90     100
169  155                  Cyndaquil   Fire       NaN    309   39      52
170  156                    Quilava   Fire       NaN    405   58      64
171  157                 Typhlosion   Fire       NaN    534   78      84
236  218                     Slugma   Fire       NaN    250   40      40
237  219                   Magcargo   Fire      Rock    410   50      50
259  240                      Magby   Fire       NaN    365   45      75
263  244                      Entei   Fire       NaN    580  115     115
270  250                      Ho-oh   Fire    Flying    680  106     130
276  255                    Torchic   Fire       NaN    310   45      60
277  256                  Combusken   Fire  Fighting    405   60      85
278  257                   Blaziken   Fire  Fighting    530   80     120
279  257      BlazikenMega Blaziken   Fire  Fighting    630   80     160
352  322                      Numel   Fire    Ground    305   60      60
353  323                   Camerupt   Fire    Ground    460   70     100
354  323      CameruptMega Camerupt   Fire    Ground    560   70     120
355  324                    Torkoal   Fire       NaN    470   70      85
435  390                   Chimchar   Fire       NaN    309   44      58
436  391                   Monferno   Fire  Fighting    405   64      78
437  392                  Infernape   Fire  Fighting    534   76     104
518  467                  Magmortar   Fire       NaN    540   75      95
542  485                    Heatran   Fire     Steel    600   91      90
557  498                      Tepig   Fire       NaN    308   65      63
558  499                    Pignite   Fire  Fighting    418   90      93
559  500                     Emboar   Fire  Fighting    528  110     123
572  513                    Pansear   Fire       NaN    316   50      53
573  514                   Simisear   Fire       NaN    498   75      98
614  554                   Darumaka   Fire       NaN    315   70      90
615  555    DarmanitanStandard Mode   Fire       NaN    480  105     140
616  555         DarmanitanZen Mode   Fire   Psychic    540  105      30
692  631                    Heatmor   Fire       NaN    484   85      97
721  653                   Fennekin   Fire       NaN    307   40      45
722  654                    Braixen   Fire       NaN    409   59      59
723  655                    Delphox   Fire   Psychic    534   75      69
730  662                Fletchinder   Fire    Flying    382   62      73
731  663                 Talonflame   Fire    Flying    499   78      81
735  667                     Litleo   Fire    Normal    369   62      50
736  668                     Pyroar   Fire    Normal    507   86      68
799  721                  Volcanion   Fire     Water    600   80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  count
4         43       60       50     65           1      False      1
5         58       80       65     80           1      False      1
6         78      109       85    100           1      False      1
7        111      130       85    100           1      False      1
8         78      159      115    100           1      False      1
42        40       50       65     65           1      False      1
43        75       81      100    100           1      False      1
63        45       70       50     60           1      False      1
64        80      100       80     95           1      False      1
83        55       65       65     90           1      False      1
84        70       80       80    105           1      False      1
135       57      100       85     93           1      False      1
147       60       95      110     65           1      False      1
158       90      125       85     90           1       True      1
169       43       60       50     65           2      False      1
170       58       80       65     80           2      False      1
171       78      109       85    100           2      False      1
236       40       70       40     20           2      False      1
237      120       80       80     30           2      False      1
259       37       70       55     83           2      False      1
263       85       90       75    100           2       True      1
270       90      110      154     90           2       True      1
276       40       70       50     45           3      False      1
277       60       85       60     55           3      False      1
278       70      110       70     80           3      False      1
279       80      130       80    100           3      False      1
352       40       65       45     35           3      False      1
353       70      105       75     40           3      False      1
354      100      145      105     20           3      False      1
355      140       85       70     20           3      False      1
435       44       58       44     61           4      False      1
436       52       78       52     81           4      False      1
437       71      104       71    108           4      False      1
518       67      125       95     83           4      False      1
542      106      130      106     77           4       True      1
557       45       45       45     45           5      False      1
558       55       70       55     55           5      False      1
559       65      100       65     65           5      False      1
572       48       53       48     64           5      False      1
573       63       98       63    101           5      False      1
614       45       15       45     50           5      False      1
615       55       30       55     95           5      False      1
616      105      140      105     55           5      False      1
692       66      105       66     65           5      False      1
721       40       62       60     60           6      False      1
722       58       90       70     73           6      False      1
723       72      114      100    104           6      False      1
730       55       56       52     84           6      False      1
731       71       74       69    126           6      False      1
735       58       73       54     72           6      False      1
736       72      109       66    106           6      False      1
799      120      130       90     70           6       True      1
Venusaur

### Sorting/Describing Data

In [44]:
# Gives column statistics (mean, std, etc.)
print(df.describe())

# Sort
print(df.sort_values('Name', ascending=False))
df.sort_values(['Type 1', 'HP'], ascending=[1,0]) # Ascending parameter set for each column

                #          HP      Attack     Defense     Sp. Atk     Sp. Def  \
count  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000
mean   362.813750   69.258750   79.001250   73.842500   72.820000   71.902500
std    208.343798   25.534669   32.457366   31.183501   32.722294   27.828916
min      1.000000    1.000000    5.000000    5.000000   10.000000   20.000000
25%    184.750000   50.000000   55.000000   50.000000   49.750000   50.000000
50%    364.500000   65.000000   75.000000   70.000000   65.000000   70.000000
75%    539.250000   80.000000  100.000000   90.000000   95.000000   90.000000
max    721.000000  255.000000  190.000000  230.000000  194.000000  230.000000

            Speed  Generation
count  800.000000   800.00000
mean    68.277500     3.32375
std     29.060474     1.66129
min      5.000000     1.00000
25%     45.000000     2.00000
50%     65.000000     3.00000
75%     90.000000     5.00000
max    180.000000     6.00000
       #                     Name   Type 1  Type 2   HP  Attack  Defense  \
794  718         Zygarde50% Forme   Dragon  Ground  108     100      121
695  634                 Zweilous     Dark  Dragon   72      85       70
46    41                    Zubat   Poison  Flying   40      45       35
631  570                    Zorua     Dark     NaN   40      65       40
632  571                  Zoroark     Dark     NaN   60     105       60
..   ...                      ...      ...     ...  ...     ...      ...
393  359          AbsolMega Absol     Dark     NaN   65     150       60
392  359                    Absol     Dark     NaN   65     130       60
68    63                     Abra  Psychic     NaN   25      20       15
511  460  AbomasnowMega Abomasnow    Grass     Ice   90     132      105
510  460                Abomasnow    Grass     Ice   90      92       75

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
794       81       95     95           6       True
695       65       70     58           5      False
46        30       40     55           1      False
631       80       40     65           5      False
632      120       60    105           5      False
..       ...      ...    ...         ...        ...
393      115       60    115           3      False
392       75       60     75           3      False
68       105       55     90           1      False
511      132      105     30           4      False
510       92       85     60           4      False

[800 rows x 12 columns]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Making Changes to Data

In [46]:
# Simple way to do it
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

# Dropping a column
df = df.drop(columns=['Total'])

# More elegant way to do it
df['Total'] = df.iloc[:, 4:10].sum(axis=1)
# (However, it is safer to get indices by column name instead of hardcoding them)

# Reorder columns
cols = list(df.columns) # Get all columns as a list
df = df[cols[0:4] + [cols[-1]] + cols[4:12]] # Move final column to position 4
# "cols[-1]" is bracketed so it can be concatenated to the other lists

df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Saving Data (Exporting into Desired Format)

In [47]:
df.to_csv('modified.csv', index=False) # index=False removes the index column

# Other formats
#df.to_excel('modified.xlsx', index=False)
#df.to_csv('modified.txt', index=False, sep='\t')

### Filtering Data

In [52]:
# Passing in multiple conditions (parentheses are necessary)
# & = AND
# | = OR
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]

# The new dataframe keeps the old indices, but can reset them
# drop=True removes column with old indices
# inplace=True avoids having to assign it to new_df
new_df.reset_index(drop=True, inplace=True) 

print(new_df)

#new_df.to_csv('filtered.csv')

# Drop all rows where Name contains 'Mega'
# ~ = NOT
print(df.loc[~df['Name'].str.contains('Mega')])

# Using regex to filter
import re

# Find rows where Type 1 is Fire or Grass
# flags=re.I ignores case in regex
print(df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)])

# Find rows where Name starts with 'pi'
df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

     #                   Name Type 1  Type 2  Total   HP  Attack  Defense  \
0    3               Venusaur  Grass  Poison    525   80      82       83
1    3  VenusaurMega Venusaur  Grass  Poison    625   80     100      123
2   45              Vileplume  Grass  Poison    490   75      80       85
3   71             Victreebel  Grass  Poison    490   80     105       65
4  591              Amoonguss  Grass  Poison    464  114      85       70

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0      100      100     80           1      False
1      122      120     80           1      False
2      110       90     50           1      False
3      100       70     70           1      False
4       85       80     30           5      False
       #                 Name   Type 1  Type 2  Total   HP  Attack  Defense  \
0      1            Bulbasaur    Grass  Poison    318   45      49       49
1      2              Ivysaur    Grass  Poison    405   60      62       63
2      3             Venusaur    Grass  Poison    525   80      82       83
4      4           Charmander     Fire     NaN    309   39      52       43
5      5           Charmeleon     Fire     NaN    405   58      64       58
..   ...                  ...      ...     ...    ...  ...     ...      ...
794  718     Zygarde50% Forme   Dragon  Ground    600  108     100      121
795  719              Diancie     Rock   Fairy    600   50     100      150
797  720  HoopaHoopa Confined  Psychic   Ghost    600   80     110       60
798  720   HoopaHoopa Unbound  Psychic    Dark    680   80     160       60
799  721            Volcanion     Fire   Water    600   80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
4         60       50     65           1      False
5         80       65     80           1      False
..       ...      ...    ...         ...        ...
794       81       95     95           6       True
795      100      150     50           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[751 rows x 13 columns]
       #                   Name Type 1  Type 2  Total   HP  Attack  Defense  \
0      1              Bulbasaur  Grass  Poison    318   45      49       49
1      2                Ivysaur  Grass  Poison    405   60      62       63
2      3               Venusaur  Grass  Poison    525   80      82       83
3      3  VenusaurMega Venusaur  Grass  Poison    625   80     100      123
4      4             Charmander   Fire     NaN    309   39      52       43
..   ...                    ...    ...     ...    ...  ...     ...      ...
735  667                 Litleo   Fire  Normal    369   62      50       58
736  668                 Pyroar   Fire  Normal    507   86      68       72
740  672                 Skiddo  Grass     NaN    350   66      65       48
741  673                 Gogoat  Grass     NaN    531  123     100       62
799  721              Volcanion   Fire   Water    600   80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
735       73       54     72           6      False
736      109       66    106           6      False
740       62       57     52           6      False
741       97       81     68           6      False
799      130       90     70           6       True

[122 rows x 13 columns]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

### Conditional Changes

In [69]:
# Change all Type 1 'Fire' to 'Flamer' (and back)
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'
df.loc[df['Type 1'] == 'Flamer', 'Type 1'] = 'Fire'

# Make all Type 1 Fire rows legendary
df.loc[df['Type 1'] == 'Fire', 'Legendary'] = True

# Change multiple columns at a time (pass in list)
df.loc[df['Total'] > 500, ['Generation','Legendary']] = ['Test 1', 'Test 2']

# Load checkpoint to reset changes
df= pd.read_csv('modified.csv')

df

C:\Users\kevin\AppData\Local\Temp\ipykernel_3936\3198375693.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Test 1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Total'] > 500, ['Generation','Legendary']] = ['Test 1', 'Test 2']
C:\Users\kevin\AppData\Local\Temp\ipykernel_3936\3198375693.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Test 2' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[df['Total'] > 500, ['Generation','Legendary']] = ['Test 1', 'Test 2']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

### Aggregate Statistics (Groupby)

In [105]:
df = pd.read_csv('modified.csv')

# Find average stats grouped by Type 1, sorted by highest defense
# Note (this wasn't in the video, but from a comment):
#   Pandas v2.0.0 changed numeric_only default value to False
#   Setting it to True ensures it won't throw errors like "can not convert strings"
print(df.groupby(['Type 1']).mean(numeric_only=True).sort_values('Defense', ascending=False))

# Find sums of stats grouped by Type 1
print(df.groupby(['Type 1']).sum(numeric_only=True))

# Find counts of each Type 1 & 2 combination
df['count'] = 1 # Give each row a count column = 1
df.groupby(['Type 1', 'Type 2']).count()['count']

                   #       Total         HP      Attack     Defense  \
Type 1
Steel     442.851852  487.703704  65.222222   92.703704  126.370370
Rock      392.727273  453.750000  65.363636   92.863636  100.795455
Dragon    474.375000  550.531250  83.312500  112.125000   86.375000
Ground    356.281250  437.500000  73.781250   95.750000   84.843750
Ghost     486.500000  439.562500  64.437500   73.781250   81.187500
Water     303.089286  430.455357  72.062500   74.151786   72.946429
Ice       423.541667  433.458333  72.000000   72.750000   71.416667
Grass     344.871429  421.142857  67.271429   73.214286   70.800000
Bug       334.492754  378.927536  56.884058   70.971014   70.724638
Dark      461.354839  445.741935  66.806452   88.387097   70.225806
Poison    251.785714  399.142857  67.250000   74.678571   68.821429
Fire      327.403846  458.076923  69.903846   84.769231   67.769231
Psychic   380.807018  475.947368  70.631579   71.456140   67.684211
Electric  363.500000  443.409091  59.795455   69.090909   66.295455
Flying    677.750000  485.000000  70.750000   78.750000   66.250000
Fighting  363.851852  416.444444  69.851852   96.777778   65.925926
Fairy     449.529412  413.176471  74.117647   61.529412   65.705882
Normal    319.173469  401.683673  77.275510   73.469388   59.846939

            Sp. Atk    Sp. Def       Speed  Generation  Legendary
Type 1
Steel     67.518519  80.629630   55.259259    3.851852   0.148148
Rock      63.340909  75.477273   55.909091    3.454545   0.090909
Dragon    96.843750  88.843750   83.031250    3.875000   0.375000
Ground    56.468750  62.750000   63.906250    3.156250   0.125000
Ghost     79.343750  76.468750   64.343750    4.187500   0.062500
Water     74.812500  70.517857   65.964286    2.857143   0.035714
Ice       77.541667  76.291667   63.458333    3.541667   0.083333
Grass     77.500000  70.428571   61.928571    3.357143   0.042857
Bug       53.869565  64.797101   61.681159    3.217391   0.000000
Dark      74.645161  69.516129   76.161290    4.032258   0.064516
Poison    60.428571  64.392857   63.571429    2.535714   0.000000
Fire      88.980769  72.211538   74.442308    3.211538   0.096154
Psychic   98.403509  86.280702   81.491228    3.385965   0.245614
Electric  90.022727  73.704545   84.500000    3.272727   0.090909
Flying    94.250000  72.500000  102.500000    5.500000   0.500000
Fighting  53.111111  64.703704   66.074074    3.370370   0.000000
Fairy     78.529412  84.705882   48.588235    4.117647   0.058824
Normal    55.816327  63.724490   71.551020    3.051020   0.020408
              #  Total    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1
Bug       23080  26146  3925    4897     4880     3717     4471   4256
Dark      14302  13818  2071    2740     2177     2314     2155   2361
Dragon    15180  17617  2666    3588     2764     3099     2843   2657
Electric  15994  19510  2631    3040     2917     3961     3243   3718
Fairy      7642   7024  1260    1046     1117     1335     1440    826
Fighting   9824  11244  1886    2613     1780     1434     1747   1784
Fire      17025  23820  3635    4408     3524     4627     3755   3871
Flying     2711   1940   283     315      265      377      290    410
Ghost     15568  14066  2062    2361     2598     2539     2447   2059
Grass     24141  29480  4709    5125     4956     5425     4930   4335
Ground    11401  14000  2361    3064     2715     1807     2008   2045
Ice       10165  10403  1728    1746     1714     1861     1831   1523
Normal    31279  39365  7573    7200     5865     5470     6245   7012
Poison     7050  11176  1883    2091     1927     1692     1803   1780
Psychic   21706  27129  4026    4073     3858     5609     4918   4645
Rock      17280  19965  2876    4086     4435     2787     3321   2460
Steel     11957  13168  1761    2503     3412     1823     2177   1492
Water     33946  48211  8071    8305     8170     8379     7898   7388

          Generation  Legendary
Type 1
Bug              222          0
Dark             125          2
Dragon           124         12
Electric         144          4
Fairy             70          1
Fighting          91          0
Fire             167          5
Flying            22          2
Ghost            134          2
Grass            235          3
Ground           101          4
Ice               85          2
Normal           299          2
Poison            71          0
Psychic          193         14
Rock             152          4
Steel            104          4
Water            320          4

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

### Working with Large Amounts of Data

In [100]:
# Create empty dataframe with same column names as original dataframe
new_df = pd.DataFrame(columns=df.columns)

# Load in data 5 rows at a time
for df in pd.read_csv('modified.csv', chunksize=5):
    results = df.groupby(['Type 1']).count()
    
    # Add on the new rows for this chunk
    new_df = pd.concat([new_df, results])

new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Fire,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Grass,4,4,NaN,4,4,4,4,4,4,4,4,4,4
Fire,4,4,NaN,3,4,4,4,4,4,4,4,4,4
Water,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Bug,2,2,NaN,0,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Fairy,1,1,NaN,0,1,1,1,1,1,1,1,1,1
Flying,2,2,NaN,2,2,2,2,2,2,2,2,2,2
Fire,1,1,NaN,1,1,1,1,1,1,1,1,1,1
Psychic,2,2,NaN,2,2,2,2,2,2,2,2,2,2
Rock,2,2,NaN,2,2,2,2,2,2,2,2,2,2